language: php
os: linux
sudo: required
dist: xenial
services:
    - mysql
before_script:
    - sudo apt-get install apache2 libapache2-mod-fastcgi
    - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
    - sudo a2enmod rewrite actions fastcgi alias
    - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - sudo sed -i -e "s,www-data,travis,g" /etc/apache2/envvars
    - sudo chown -R travis:travis /var/lib/apache2/fastcgi
    - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
    - sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place travis-ci-apache.conf
    - sudo cp -f travis-ci-apache.conf /etc/apache2/sites-available/000-default.conf
    - sudo service apache2 restart
    - mysql < db.sql
install:
    - cp mysql-sample.php mysql.php
    